
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 33;
  public static final int LPAREN = 30;
  public static final int INT = 12;
  public static final int MINUS = 28;
  public static final int STATIC = 4;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 32;
  public static final int AND = 25;
  public static final int LTHAN = 22;
  public static final int LCURLYBRACE = 35;
  public static final int CLASS = 7;
  public static final int PLUS = 26;
  public static final int MAIN = 6;
  public static final int IF = 16;
  public static final int EXCLAMATION = 24;
  public static final int THIS = 10;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 19;
  public static final int RBRACKET = 34;
  public static final int TRUE = 14;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int BECOMES = 27;
  public static final int VOID = 5;
  public static final int INTLITERAL = 39;
  public static final int ELSE = 17;
  public static final int WHILE = 18;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 8;
  public static final int MULTI = 29;
  public static final int STRING = 11;
  public static final int FALSE = 15;
  public static final int RCURLYBRACE = 36;
  public static final int PRINT = 21;
  public static final int LENGTH = 20;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "CLASS",
  "EXTENDS",
  "NEW",
  "THIS",
  "STRING",
  "INT",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LENGTH",
  "PRINT",
  "LTHAN",
  "DOT",
  "EXCLAMATION",
  "AND",
  "PLUS",
  "BECOMES",
  "MINUS",
  "MULTI",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "LCURLYBRACE",
  "RCURLYBRACE",
  "COMA",
  "IDENTIFIER",
  "INTLITERAL"
  };
}

